### ISSUE TITLE
Incorrect "title" attribute of cell after using inline edit and formatter "select"

### ISSUE THREAD

**Issue by zohanalexix** [free-jqgrid/free-jqgrid.github.io#10]
I noticed that after editing inline fields of type "select", the value of the select is set as "title" of the <td> element, instead of the text associated with the value. 
```
{name:'select', editable:true, edittype:'select', formatter:'select', 
 editoptions:{value:'1000000:AAA;1000001:BBB;1000002:CCC'}}
```
![incorect title attribute](https://user-images.githubusercontent.com/18122792/26932942-c81150f6-4c6d-11e7-844f-a86e2e865b3c.png)
Demo: https://jsfiddle.net/zohalexix/d0h5jc7y/1/

I assume this is a bug. Is there any easy-fix for it?

**Comment by OlegKi** [comment]
Thank you for the bug report! I posted [the fix](https://github.com/free-jqgrid/jqGrid/commit/bde41abecda11c9a73b3ff6c9f8e3a4cb82c0743) to GitHub. 

See the demo https://jsfiddle.net/OlegKi/d0h5jc7y/4/, which uses the latest code from GitHub.

Small additional remark: please use https://github.com/free-jqgrid/jqGrid/issues to report issues about "free jqGrid" and https://github.com/free-jqgrid/free-jqgrid.github.io/issues to report issues in documentation of free jqGrid.

**Comment by zohanalexix** [comment]
Thanks for the fix and sorry for posting the issue in the wrong repository.

You can try to move the issue using https://github.com/google/github-issue-mover
