### ISSUE TITLE
Why do I see the code permissions not?

### ISSUE THREAD

**Issue by jinchunhe** [free-jqgrid/free-jqgrid.github.io#4]
Why do I see the code permissions not?

**Comment by OlegKi** [comment]
Sorry, I don't understand what you mean. I will publish under `free-jqgrid.github.io` **the documentation** to [free jqGrid](https://github.com/free-jqgrid/jqGrid). Currently the documentation is in [the wiki](https://github.com/free-jqgrid/jqGrid/wiki).
