### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by dannyweldon** [free-jqgrid/free-jqgrid.github.io#5]
It would be good if you could have a few demos, even if you just listed the code to a basic sample with static data on the github home page under the example of how to include the library and provide a screenshot.

This is because I came across your fork but couldn't find an example to try it out.  I did try an example from somewhere else but it was based on the non-free jqgrid and it didn't work.

**Comment by OlegKi** [comment]
Do you seen [the page](https://free-jqgrid.github.io/getting-started/index.html) and [this one](https://free-jqgrid.github.io/examples/index.html)? The first one provides some simple code examples with the corresponding descriptions. The second one demonstrates some new features implemented in free jqGrid. The screen shorts will be displayed if you check "Show image" checkboxes on the page.

There are some demos in many answers on [the stackoverflow](http://stackoverflow.com/questions/tagged/free-jqgrid).

**Comment by dannyweldon** [comment]
Would you accept a PR if I updated the github README.md and put those links on it under a heading?

**Comment by OlegKi** [comment]
I'm not sure what you mean with updating of README. All *.github.io repositories are the soure of the corresponding web sites (see, for example, https://github.com/select2/select2.github.io/ and https://select2.github.io/). The main repository of free jqGrid is https://github.com/free-jqgrid/jqGrid. The README of the repository contains the reference to [the wiki](https://github.com/free-jqgrid/jqGrid/wiki) and the reference to http://free-jqgrid.github.io/ as "the preliminary version of the documentation".

In any way I modified the "header" of the repository and I'm closing the issue.
